const LOL_SETTING = {
    "sourceWorkbook":  "Tool League of Legends.live.xlsx",
    "sourceSheet":  "Setting",
    "generatedAt":  "2026-07-07 08:34:11",
    "ranges":  {
                   "language":  "B3:B3",
                   "lanes":  "N4:N8",
                   "positiveFormation":  "O4:O7",
                   "damageTypes":  "P4:P15",
                   "skillChampTypes":  "Q4:Q182",
                   "typeSkill":  "S4:S219",
                   "classes":  "I4:I10",
                   "subclassesA":  "J4:J10",
                   "subclassesB":  "K4:K10",
                   "combatTypes":  "E4:E6",
                   "macroTypes":  "D4:D6",
                   "allChampions":  "X3:X219",
                   "teamBlueTopOptions":  "CQ3:CQ182",
                   "teamBlueJungleOptions":  "CR3:CR182",
                   "teamBlueMidOptions":  "CS3:CS182",
                   "teamBlueAdOptions":  "CT3:CT182",
                   "teamBlueSupportOptions":  "CU3:CU182",
                   "checkFeature1":  "CF3:CF219",
                   "checkFeature2":  "CG3:CG219",
                   "checkFeature3":  "CH3:CH219",
                   "checkFeature4":  "CI3:CI219",
                   "checkFeature5":  "CJ3:CJ219",
                   "checkCounter1":  "CK3:CK219",
                   "checkCounter2":  "CL3:CL219",
                   "checkCounter3":  "CM3:CM219",
                   "checkCounter4":  "CN3:CN219",
                   "checkCounter5":  "CO3:CO219",
                   "banPickChampionPool":  "DE3:DE179",
                   "banPickTopPool":  "CW3:CW179",
                   "banPickJunglePool":  "CX3:CX179",
                   "banPickOtherPool":  "CY3:CY179",
                   "banPickMode":  "DI2:DM2"
               },
    "named":  {
                  "language":  "vi",
                  "lanes":  [
                                "Top",
                                "Jungle",
                                "Mid",
                                "ADC",
                                "Support"
                            ],
                  "positiveFormation":  [
                                            "Frontline",
                                            "Midline",
                                            "Backline",
                                            "Flank"
                                        ],
                  "damageTypes":  [
                                      "Burst AD",
                                      "Burst AD\u0026AP",
                                      "Burst AP",
                                      "Burst Dps AD",
                                      "Burst Dps AP",
                                      "Dps AD",
                                      "Dps AD\u0026AP",
                                      "Dps AP",
                                      "Tank",
                                      "Semi Tank AD",
                                      "Semi Tank AP",
                                      "Buff"
                                  ],
                  "skillChampTypes":  [
                                          "CC",
                                          "CC Hard",
                                          "Slow",
                                          "Mobility",
                                          "Control",
                                          "Dive",
                                          "Pick",
                                          "Scaling",
                                          "Woocombo",
                                          "Engage",
                                          "Buff",
                                          "Imba",
                                          "Heal",
                                          "Shield",
                                          "Hook",
                                          "Global",
                                          "0",
                                          "1"
                                      ],
                  "typeSkill":  [
                                    "Airborne",
                                    "Aoe",
                                    "Armor penetration",
                                    "Auto Target",
                                    "Banishing",
                                    "Berserk",
                                    "Blink",
                                    "Bonus Armor",
                                    "Bonus AS",
                                    "Bonus Dame",
                                    "Bonus Heal",
                                    "Bonus Heal Regeneration",
                                    "Bonus Health",
                                    "Bonus Magic Resistance",
                                    "Bonus Mana Regeneration",
                                    "Brush",
                                    "Buff AS",
                                    "Buff Heal",
                                    "Buff Resurrection",
                                    "Buff Shield",
                                    "Buff Speed",
                                    "Burst Dame",
                                    "Camouflage",
                                    "Charm",
                                    "Clearwave",
                                    "Clone",
                                    "Copy",
                                    "Cover",
                                    "Cripple",
                                    "Crowd Control Effects",
                                    "Dash",
                                    "Death",
                                    "Debuff",
                                    "Destroy Shields",
                                    "Displacement Immunity",
                                    "Disrupt",
                                    "Dive",
                                    "Dps",
                                    "Drowsy",
                                    "Execute",
                                    "Exp",
                                    "Fear / Flee",
                                    "Global",
                                    "Gold",
                                    "Grievous Wounds",
                                    "Heal",
                                    "Health regeneration",
                                    "Hook",
                                    "Imba",
                                    "Immobilizing",
                                    "Immunity",
                                    "Invisibility",
                                    "Invulnerability",
                                    "Item",
                                    "Kinematics",
                                    "Knockdown",
                                    "Life steal",
                                    "Lunge",
                                    "Mana",
                                    "Magic penetration",
                                    "Nearsight",
                                    "Non-Projectile",
                                    "Omnivamp",
                                    "On-Hit",
                                    "Oracle Lens",
                                    "Pet",
                                    "Pick",
                                    "Poisoned",
                                    "Poke",
                                    "Polymorph",
                                    "Projectile",
                                    "Push Tower",
                                    "Range",
                                    "Removal",
                                    "Reset",
                                    "Resurrection",
                                    "Root",
                                    "Scaling",
                                    "Shield",
                                    "Sight",
                                    "Silence",
                                    "Sleep",
                                    "Slow",
                                    "Snare / Root",
                                    "Speed",
                                    "Spell shield",
                                    "Stasis",
                                    "Stun",
                                    "Suppression",
                                    "Takedown",
                                    "Taunt",
                                    "Tenacity",
                                    "Tower",
                                    "Trap",
                                    "True Dame",
                                    "Uncancellable Windup",
                                    "Untargetability",
                                    "Vanish",
                                    "Ward",
                                    "Zombie states",
                                    "Wall",
                                    "Tether",
                                    "Bonus Speed",
                                    "Ground",
                                    "minimum health threshold",
                                    "Blind",
                                    "Bonus Shield",
                                    "Bleed",
                                    "Buff Dame",
                                    "Buff Magic Resistance",
                                    "Dodge",
                                    "Block",
                                    "Disarm",
                                    "Strong Ult",
                                    "TeamFight",
                                    "Engage",
                                    "Disengage"
                                ],
                  "classes":  [
                                  "Controller",
                                  "Fighter",
                                  "Mage",
                                  "Marksman",
                                  "Slayer",
                                  "Tank",
                                  "Specialist"
                              ],
                  "subclassesA":  [
                                      "Enchanter",
                                      "Juggernaut",
                                      "Burst",
                                      "Assassin",
                                      "Vanguard"
                                  ],
                  "subclassesB":  [
                                      "Catcher",
                                      "Diver",
                                      "Battlemage",
                                      "Skirmisher",
                                      "Warden"
                                  ],
                  "combatTypes":  [
                                      "Engage",
                                      "Disengage",
                                      "Poke"
                                  ],
                  "macroTypes":  [
                                     "Split",
                                     "Catch",
                                     "Flex"
                                 ],
                  "allChampions":  [
                                       "Aatrox",
                                       "Ahri",
                                       "Akali",
                                       "Akshan",
                                       "Alistar",
                                       "Ambessa",
                                       "Amumu",
                                       "Anivia",
                                       "Annie",
                                       "Aphelios",
                                       "Ashe",
                                       "Aurelionsol",
                                       "Aurora",
                                       "Azir",
                                       "Bard",
                                       "Bel\u0027Veth",
                                       "Blitzcrank",
                                       "Brand",
                                       "Braum",
                                       "Briar",
                                       "Caitlyn",
                                       "Camille",
                                       "Cassiopeia",
                                       "Cho\u0027Gath",
                                       "Corki",
                                       "Darius",
                                       "Diana",
                                       "Dr.Mundo",
                                       "Draven",
                                       "Ekko",
                                       "Elise",
                                       "Evelynn",
                                       "Ezreal",
                                       "Fiddlesticks",
                                       "Fiora",
                                       "Fizz",
                                       "Galio",
                                       "Gangplank",
                                       "Garen",
                                       "Gnar",
                                       "Gragas",
                                       "Graves",
                                       "Gwen",
                                       "Hecarim",
                                       "Heimerdinger",
                                       "Hwei",
                                       "Illaoi",
                                       "Irelia",
                                       "Ivern",
                                       "Janna",
                                       "Jarvaniv",
                                       "Jax",
                                       "Jayce",
                                       "Jhin",
                                       "Jinx",
                                       "K\u0027Sante",
                                       "Kai\u0027Sa",
                                       "Kalista",
                                       "Karma",
                                       "Karthus",
                                       "Kassadin",
                                       "Katarina",
                                       "Kayle",
                                       "Kayn",
                                       "Kennen",
                                       "Kha\u0027Zix",
                                       "Kindred",
                                       "Kled",
                                       "Kled \u0026 Skaarl",
                                       "Kog\u0027Maw",
                                       "Leblanc",
                                       "Leesin",
                                       "Leona",
                                       "Lillia",
                                       "Lissandra",
                                       "Lucian",
                                       "Lulu",
                                       "Lux",
                                       "Malphite",
                                       "Malzahar",
                                       "Maokai",
                                       "Masteryi",
                                       "Mega Gnar",
                                       "Mel",
                                       "Milio",
                                       "Missfortune",
                                       "Mordekaiser",
                                       "Morgana",
                                       "Naafiri",
                                       "Nami",
                                       "Nasus",
                                       "Nautilus",
                                       "Neeko",
                                       "Nidalee",
                                       "Nilah",
                                       "Nocturne",
                                       "Nunu",
                                       "Olaf",
                                       "Orianna",
                                       "Ornn",
                                       "Pantheon",
                                       "Poppy",
                                       "Pyke",
                                       "Qiyana",
                                       "Quinn",
                                       "Rakan",
                                       "Rammus",
                                       "Rek\u0027Sai",
                                       "Rell",
                                       "Renataglasc",
                                       "Renekton",
                                       "Rengar",
                                       "Riven",
                                       "Rumble",
                                       "Ryze",
                                       "Samira",
                                       "Sejuani",
                                       "Senna",
                                       "Seraphine",
                                       "Sett",
                                       "Shaco",
                                       "Shen",
                                       "Shyvana",
                                       "Singed",
                                       "Sion",
                                       "Sivir",
                                       "Skarner",
                                       "Smolder",
                                       "Sona",
                                       "Soraka",
                                       "Swain",
                                       "Sylas",
                                       "Syndra",
                                       "Tahmkench",
                                       "Taliyah",
                                       "Talon",
                                       "Taric",
                                       "Teemo",
                                       "Thresh",
                                       "Tristana",
                                       "Trundle",
                                       "Tryndamere",
                                       "Twistedfate",
                                       "Twitch",
                                       "Udyr",
                                       "Urgot",
                                       "Varus",
                                       "Vayne",
                                       "Veigar",
                                       "Vel\u0027Koz",
                                       "Vex",
                                       "Vi",
                                       "Viego",
                                       "Viktor",
                                       "Vladimir",
                                       "Volibear",
                                       "Warwick",
                                       "Wukong",
                                       "Xayah",
                                       "Xerath",
                                       "Xinzhao",
                                       "Yasuo",
                                       "Yone",
                                       "Yorick",
                                       "Yunara",
                                       "Yuumi",
                                       "Zac",
                                       "Zed",
                                       "Zeri",
                                       "Ziggs",
                                       "Zilean",
                                       "Zoe",
                                       "Zyra"
                                   ],
                  "teamBlueTopOptions":  [
                                             "Aatrox",
                                             "Akali",
                                             "Ambessa",
                                             "Aurora",
                                             "Camille",
                                             "Cassiopeia",
                                             "Cho\u0027Gath",
                                             "Darius",
                                             "Dr.Mundo",
                                             "Elise",
                                             "Fiora",
                                             "Galio",
                                             "Gangplank",
                                             "Garen",
                                             "Gnar",
                                             "Gragas",
                                             "Gwen",
                                             "Heimerdinger",
                                             "Illaoi",
                                             "Irelia",
                                             "Jax",
                                             "Jayce",
                                             "K\u0027Sante",
                                             "Kalista",
                                             "Karma",
                                             "Kayle",
                                             "Kennen",
                                             "Kled",
                                             "Kled \u0026 Skaarl",
                                             "Malphite",
                                             "Maokai",
                                             "Mega Gnar",
                                             "Mordekaiser",
                                             "Nasus",
                                             "Nidalee",
                                             "Olaf",
                                             "Ornn",
                                             "Pantheon",
                                             "Poppy",
                                             "Quinn",
                                             "Rammus",
                                             "Rek\u0027Sai",
                                             "Renekton",
                                             "Rengar",
                                             "Riven",
                                             "Rumble",
                                             "Ryze",
                                             "Sejuani",
                                             "Sett",
                                             "Shen",
                                             "Singed",
                                             "Sion",
                                             "Skarner",
                                             "Smolder",
                                             "Swain",
                                             "Sylas",
                                             "TahmKench",
                                             "Teemo",
                                             "Trundle",
                                             "Tryndamere",
                                             "TwistedFate",
                                             "Udyr",
                                             "Urgot",
                                             "Vayne",
                                             "Vladimir",
                                             "Volibear",
                                             "Warwick",
                                             "Wukong",
                                             "Yasuo",
                                             "Yone",
                                             "Yorick",
                                             "Zac"
                                         ],
                  "teamBlueJungleOptions":  [
                                                "Amumu",
                                                "Bel\u0027Veth",
                                                "Brand",
                                                "Briar",
                                                "Darius",
                                                "Diana",
                                                "Dr.Mundo",
                                                "Ekko",
                                                "Elise",
                                                "Evelynn",
                                                "Fiddlesticks",
                                                "Gragas",
                                                "Graves",
                                                "Gwen",
                                                "Hecarim",
                                                "Ivern",
                                                "JarvanIV",
                                                "Jax",
                                                "Karthus",
                                                "Kayn",
                                                "Kha\u0027Zix",
                                                "Kindred",
                                                "LeeSin",
                                                "Lillia",
                                                "Malphite",
                                                "Maokai",
                                                "MasterYi",
                                                "Morgana",
                                                "Naafiri",
                                                "Nidalee",
                                                "Nocturne",
                                                "Nunu",
                                                "Olaf",
                                                "Pantheon",
                                                "Poppy",
                                                "Qiyana",
                                                "Rammus",
                                                "Rek\u0027Sai",
                                                "Rengar",
                                                "Sejuani",
                                                "Shaco",
                                                "Shyvana",
                                                "Skarner",
                                                "Sylas",
                                                "Taliyah",
                                                "Talon",
                                                "Teemo",
                                                "Trundle",
                                                "Udyr",
                                                "Vi",
                                                "Viego",
                                                "Volibear",
                                                "Warwick",
                                                "Wukong",
                                                "XinZhao",
                                                "Zac",
                                                "Zed",
                                                "Zyra"
                                            ],
                  "teamBlueMidOptions":  [
                                             "Ahri",
                                             "Akali",
                                             "Akshan",
                                             "Anivia",
                                             "Annie",
                                             "AurelionSol",
                                             "Aurora",
                                             "Azir",
                                             "Cassiopeia",
                                             "Corki",
                                             "Diana",
                                             "Ekko",
                                             "Ezreal",
                                             "Fizz",
                                             "Galio",
                                             "Gragas",
                                             "Heimerdinger",
                                             "Hwei",
                                             "Irelia",
                                             "Jayce",
                                             "Karma",
                                             "Kassadin",
                                             "Katarina",
                                             "LeBlanc",
                                             "Lissandra",
                                             "Lux",
                                             "Malphite",
                                             "Malzahar",
                                             "Mel",
                                             "Naafiri",
                                             "Nasus",
                                             "Neeko",
                                             "Nunu",
                                             "Orianna",
                                             "Pantheon",
                                             "Pyke",
                                             "Qiyana",
                                             "Renekton",
                                             "Riven",
                                             "Rumble",
                                             "Ryze",
                                             "Sion",
                                             "Smolder",
                                             "Swain",
                                             "Sylas",
                                             "Syndra",
                                             "Taliyah",
                                             "Talon",
                                             "Tristana",
                                             "TwistedFate",
                                             "Varus",
                                             "Veigar",
                                             "Vel\u0027Koz",
                                             "Vex",
                                             "Viktor",
                                             "Vladimir",
                                             "Xerath",
                                             "Yasuo",
                                             "Yone",
                                             "Zac",
                                             "Zed",
                                             "Ziggs",
                                             "Zilean",
                                             "Zoe"
                                         ],
                  "teamBlueAdOptions":  [
                                            "Aphelios",
                                            "Ashe",
                                            "Caitlyn",
                                            "Corki",
                                            "Draven",
                                            "Ezreal",
                                            "Jhin",
                                            "Jinx",
                                            "Kai\u0027Sa",
                                            "Kalista",
                                            "Kog\u0027Maw",
                                            "Lucian",
                                            "MissFortune",
                                            "Nilah",
                                            "Samira",
                                            "Senna",
                                            "Seraphine",
                                            "Sivir",
                                            "Smolder",
                                            "Tristana",
                                            "TwistedFate",
                                            "Twitch",
                                            "Varus",
                                            "Vayne",
                                            "Xayah",
                                            "Yasuo",
                                            "Yunara",
                                            "Zeri",
                                            "Ziggs"
                                        ],
                  "teamBlueSupportOptions":  [
                                                 "Alistar",
                                                 "Annie",
                                                 "Ashe",
                                                 "Bard",
                                                 "Blitzcrank",
                                                 "Brand",
                                                 "Braum",
                                                 "Camille",
                                                 "Elise",
                                                 "Galio",
                                                 "Gragas",
                                                 "Heimerdinger",
                                                 "Hwei",
                                                 "Janna",
                                                 "Karma",
                                                 "LeBlanc",
                                                 "Leona",
                                                 "Lulu",
                                                 "Lux",
                                                 "Malphite",
                                                 "Maokai",
                                                 "Mel",
                                                 "Milio",
                                                 "MissFortune",
                                                 "Morgana",
                                                 "Nami",
                                                 "Nautilus",
                                                 "Neeko",
                                                 "Pantheon",
                                                 "Poppy",
                                                 "Pyke",
                                                 "Qiyana",
                                                 "Rakan",
                                                 "Rell",
                                                 "RenataGlasc",
                                                 "Senna",
                                                 "Seraphine",
                                                 "Sett",
                                                 "Shaco",
                                                 "Shen",
                                                 "Sona",
                                                 "Soraka",
                                                 "Swain",
                                                 "Sylas",
                                                 "TahmKench",
                                                 "Taric",
                                                 "Teemo",
                                                 "Thresh",
                                                 "Twitch",
                                                 "Veigar",
                                                 "Vel\u0027Koz",
                                                 "Xerath",
                                                 "Yuumi",
                                                 "Zilean",
                                                 "Zyra"
                                             ],
                  "checkFeature1":  {

                                    },
                  "checkFeature2":  {

                                    },
                  "checkFeature3":  {

                                    },
                  "checkFeature4":  {

                                    },
                  "checkFeature5":  {

                                    },
                  "checkCounter1":  {

                                    },
                  "checkCounter2":  {

                                    },
                  "checkCounter3":  {

                                    },
                  "checkCounter4":  {

                                    },
                  "checkCounter5":  {

                                    },
                  "banPickChampionPool":  [
                                              "Trundle",
                                              "LeeSin",
                                              "JarvanIV",
                                              "Diana",
                                              "Shyvana",
                                              "Amumu",
                                              "Wukong",
                                              "Viego",
                                              "Vi",
                                              "Kha\u0027Zix",
                                              "Briar",
                                              "Dr.Mundo",
                                              "Ekko",
                                              "Fiddlesticks",
                                              "Gwen",
                                              "Kayn",
                                              "Nocturne",
                                              "Nunu",
                                              "Rammus",
                                              "Warwick",
                                              "XinZhao"
                                          ],
                  "banPickTopPool":  [
                                         "Aatrox",
                                         "Ahri",
                                         "Akali",
                                         "Akshan",
                                         "Alistar",
                                         "Ambessa",
                                         "Amumu",
                                         "Anivia",
                                         "Annie",
                                         "Aphelios",
                                         "Ashe",
                                         "AurelionSol",
                                         "Aurora",
                                         "Azir",
                                         "Bard",
                                         "Bel\u0027Veth",
                                         "Blitzcrank",
                                         "Brand",
                                         "Braum",
                                         "Briar",
                                         "Caitlyn",
                                         "Camille",
                                         "Cassiopeia",
                                         "Cho\u0027Gath",
                                         "Corki",
                                         "Darius",
                                         "Diana",
                                         "Dr.Mundo",
                                         "Draven",
                                         "Ekko",
                                         "Elise",
                                         "Evelynn",
                                         "Ezreal",
                                         "Fiddlesticks",
                                         "Fiora",
                                         "Fizz",
                                         "Galio",
                                         "Gangplank",
                                         "Garen",
                                         "Gnar",
                                         "Gragas",
                                         "Graves",
                                         "Gwen",
                                         "Hecarim",
                                         "Heimerdinger",
                                         "Hwei",
                                         "Illaoi",
                                         "Irelia",
                                         "Ivern",
                                         "Janna",
                                         "JarvanIV",
                                         "Jax",
                                         "Jayce",
                                         "Jhin",
                                         "Jinx",
                                         "K\u0027Sante",
                                         "Kai\u0027Sa",
                                         "Kalista",
                                         "Karma",
                                         "Karthus",
                                         "Kassadin",
                                         "Katarina",
                                         "Kayle",
                                         "Kayn",
                                         "Kennen",
                                         "Kha\u0027Zix",
                                         "Kindred",
                                         "Kled",
                                         "Kled \u0026 Skaarl",
                                         "Kog\u0027Maw",
                                         "LeBlanc",
                                         "LeeSin",
                                         "Leona",
                                         "Lillia",
                                         "Lissandra",
                                         "Lucian",
                                         "Lulu",
                                         "Lux",
                                         "Malphite",
                                         "Malzahar",
                                         "Maokai",
                                         "MasterYi",
                                         "Mega Gnar",
                                         "Mel",
                                         "Milio",
                                         "MissFortune",
                                         "Mordekaiser",
                                         "Morgana",
                                         "Naafiri",
                                         "Nami",
                                         "Nasus",
                                         "Nautilus",
                                         "Neeko",
                                         "Nidalee",
                                         "Nilah",
                                         "Nocturne",
                                         "Nunu",
                                         "Olaf",
                                         "Orianna",
                                         "Ornn",
                                         "Pantheon",
                                         "Poppy",
                                         "Pyke",
                                         "Qiyana",
                                         "Quinn",
                                         "Rakan",
                                         "Rammus",
                                         "Rek\u0027Sai",
                                         "Rell",
                                         "RenataGlasc",
                                         "Renekton",
                                         "Rengar",
                                         "Riven",
                                         "Rumble",
                                         "Ryze",
                                         "Samira",
                                         "Sejuani",
                                         "Senna",
                                         "Seraphine",
                                         "Sett",
                                         "Shaco",
                                         "Shen",
                                         "Shyvana",
                                         "Singed",
                                         "Sion",
                                         "Sivir",
                                         "Skarner",
                                         "Smolder",
                                         "Sona",
                                         "Soraka",
                                         "Swain",
                                         "Sylas",
                                         "Syndra",
                                         "TahmKench",
                                         "Taliyah",
                                         "Talon",
                                         "Taric",
                                         "Teemo",
                                         "Thresh",
                                         "Tristana",
                                         "Trundle",
                                         "Tryndamere",
                                         "TwistedFate",
                                         "Twitch",
                                         "Udyr",
                                         "Urgot",
                                         "Varus",
                                         "Vayne",
                                         "Veigar",
                                         "Vel\u0027Koz",
                                         "Vex",
                                         "Vi",
                                         "Viego",
                                         "Viktor",
                                         "Vladimir",
                                         "Volibear",
                                         "Warwick",
                                         "Wukong",
                                         "Xayah",
                                         "Xerath",
                                         "XinZhao",
                                         "Yasuo",
                                         "Yone",
                                         "Yorick",
                                         "Yunara",
                                         "Yuumi",
                                         "Zac",
                                         "Zed",
                                         "Zeri",
                                         "Ziggs",
                                         "Zilean",
                                         "Zoe",
                                         "Zyra"
                                     ],
                  "banPickJunglePool":  [
                                            "Aatrox",
                                            "Ahri",
                                            "Akali",
                                            "Akshan",
                                            "Alistar",
                                            "Ambessa",
                                            "Amumu",
                                            "Anivia",
                                            "Annie",
                                            "Aphelios",
                                            "Ashe",
                                            "AurelionSol",
                                            "Aurora",
                                            "Azir",
                                            "Bard",
                                            "Bel\u0027Veth",
                                            "Blitzcrank",
                                            "Brand",
                                            "Braum",
                                            "Briar",
                                            "Caitlyn",
                                            "Camille",
                                            "Cassiopeia",
                                            "Cho\u0027Gath",
                                            "Corki",
                                            "Darius",
                                            "Diana",
                                            "Dr.Mundo",
                                            "Draven",
                                            "Ekko",
                                            "Elise",
                                            "Evelynn",
                                            "Ezreal",
                                            "Fiddlesticks",
                                            "Fiora",
                                            "Fizz",
                                            "Galio",
                                            "Gangplank",
                                            "Garen",
                                            "Gnar",
                                            "Gragas",
                                            "Graves",
                                            "Gwen",
                                            "Hecarim",
                                            "Heimerdinger",
                                            "Hwei",
                                            "Illaoi",
                                            "Irelia",
                                            "Ivern",
                                            "Janna",
                                            "JarvanIV",
                                            "Jax",
                                            "Jayce",
                                            "Jhin",
                                            "Jinx",
                                            "K\u0027Sante",
                                            "Kai\u0027Sa",
                                            "Kalista",
                                            "Karma",
                                            "Karthus",
                                            "Kassadin",
                                            "Katarina",
                                            "Kayle",
                                            "Kayn",
                                            "Kennen",
                                            "Kha\u0027Zix",
                                            "Kindred",
                                            "Kled",
                                            "Kled \u0026 Skaarl",
                                            "Kog\u0027Maw",
                                            "LeBlanc",
                                            "LeeSin",
                                            "Leona",
                                            "Lillia",
                                            "Lissandra",
                                            "Lucian",
                                            "Lulu",
                                            "Lux",
                                            "Malphite",
                                            "Malzahar",
                                            "Maokai",
                                            "MasterYi",
                                            "Mega Gnar",
                                            "Mel",
                                            "Milio",
                                            "MissFortune",
                                            "Mordekaiser",
                                            "Morgana",
                                            "Naafiri",
                                            "Nami",
                                            "Nasus",
                                            "Nautilus",
                                            "Neeko",
                                            "Nidalee",
                                            "Nilah",
                                            "Nocturne",
                                            "Nunu",
                                            "Olaf",
                                            "Orianna",
                                            "Ornn",
                                            "Pantheon",
                                            "Poppy",
                                            "Pyke",
                                            "Qiyana",
                                            "Quinn",
                                            "Rakan",
                                            "Rammus",
                                            "Rek\u0027Sai",
                                            "Rell",
                                            "RenataGlasc",
                                            "Renekton",
                                            "Rengar",
                                            "Riven",
                                            "Rumble",
                                            "Ryze",
                                            "Samira",
                                            "Sejuani",
                                            "Senna",
                                            "Seraphine",
                                            "Sett",
                                            "Shaco",
                                            "Shen",
                                            "Shyvana",
                                            "Singed",
                                            "Sion",
                                            "Sivir",
                                            "Skarner",
                                            "Smolder",
                                            "Sona",
                                            "Soraka",
                                            "Swain",
                                            "Sylas",
                                            "Syndra",
                                            "TahmKench",
                                            "Taliyah",
                                            "Talon",
                                            "Taric",
                                            "Teemo",
                                            "Thresh",
                                            "Tristana",
                                            "Trundle",
                                            "Tryndamere",
                                            "TwistedFate",
                                            "Twitch",
                                            "Udyr",
                                            "Urgot",
                                            "Varus",
                                            "Vayne",
                                            "Veigar",
                                            "Vel\u0027Koz",
                                            "Vex",
                                            "Vi",
                                            "Viego",
                                            "Viktor",
                                            "Vladimir",
                                            "Volibear",
                                            "Warwick",
                                            "Wukong",
                                            "Xayah",
                                            "Xerath",
                                            "XinZhao",
                                            "Yasuo",
                                            "Yone",
                                            "Yorick",
                                            "Yunara",
                                            "Yuumi",
                                            "Zac",
                                            "Zed",
                                            "Zeri",
                                            "Ziggs",
                                            "Zilean",
                                            "Zoe",
                                            "Zyra"
                                        ],
                  "banPickOtherPool":  [
                                           "Aatrox",
                                           "Ahri",
                                           "Akali",
                                           "Akshan",
                                           "Alistar",
                                           "Ambessa",
                                           "Amumu",
                                           "Anivia",
                                           "Annie",
                                           "Aphelios",
                                           "Ashe",
                                           "AurelionSol",
                                           "Aurora",
                                           "Azir",
                                           "Bard",
                                           "Bel\u0027Veth",
                                           "Blitzcrank",
                                           "Brand",
                                           "Braum",
                                           "Briar",
                                           "Caitlyn",
                                           "Camille",
                                           "Cassiopeia",
                                           "Cho\u0027Gath",
                                           "Corki",
                                           "Darius",
                                           "Diana",
                                           "Dr.Mundo",
                                           "Draven",
                                           "Ekko",
                                           "Elise",
                                           "Evelynn",
                                           "Ezreal",
                                           "Fiddlesticks",
                                           "Fiora",
                                           "Fizz",
                                           "Galio",
                                           "Gangplank",
                                           "Garen",
                                           "Gnar",
                                           "Gragas",
                                           "Graves",
                                           "Gwen",
                                           "Hecarim",
                                           "Heimerdinger",
                                           "Hwei",
                                           "Illaoi",
                                           "Irelia",
                                           "Ivern",
                                           "Janna",
                                           "JarvanIV",
                                           "Jax",
                                           "Jayce",
                                           "Jhin",
                                           "Jinx",
                                           "K\u0027Sante",
                                           "Kai\u0027Sa",
                                           "Kalista",
                                           "Karma",
                                           "Karthus",
                                           "Kassadin",
                                           "Katarina",
                                           "Kayle",
                                           "Kayn",
                                           "Kennen",
                                           "Kha\u0027Zix",
                                           "Kindred",
                                           "Kled",
                                           "Kled \u0026 Skaarl",
                                           "Kog\u0027Maw",
                                           "LeBlanc",
                                           "LeeSin",
                                           "Leona",
                                           "Lillia",
                                           "Lissandra",
                                           "Lucian",
                                           "Lulu",
                                           "Lux",
                                           "Malphite",
                                           "Malzahar",
                                           "Maokai",
                                           "MasterYi",
                                           "Mega Gnar",
                                           "Mel",
                                           "Milio",
                                           "MissFortune",
                                           "Mordekaiser",
                                           "Morgana",
                                           "Naafiri",
                                           "Nami",
                                           "Nasus",
                                           "Nautilus",
                                           "Neeko",
                                           "Nidalee",
                                           "Nilah",
                                           "Nocturne",
                                           "Nunu",
                                           "Olaf",
                                           "Orianna",
                                           "Ornn",
                                           "Pantheon",
                                           "Poppy",
                                           "Pyke",
                                           "Qiyana",
                                           "Quinn",
                                           "Rakan",
                                           "Rammus",
                                           "Rek\u0027Sai",
                                           "Rell",
                                           "RenataGlasc",
                                           "Renekton",
                                           "Rengar",
                                           "Riven",
                                           "Rumble",
                                           "Ryze",
                                           "Samira",
                                           "Sejuani",
                                           "Senna",
                                           "Seraphine",
                                           "Sett",
                                           "Shaco",
                                           "Shen",
                                           "Shyvana",
                                           "Singed",
                                           "Sion",
                                           "Sivir",
                                           "Skarner",
                                           "Smolder",
                                           "Sona",
                                           "Soraka",
                                           "Swain",
                                           "Sylas",
                                           "Syndra",
                                           "TahmKench",
                                           "Taliyah",
                                           "Talon",
                                           "Taric",
                                           "Teemo",
                                           "Thresh",
                                           "Tristana",
                                           "Trundle",
                                           "Tryndamere",
                                           "TwistedFate",
                                           "Twitch",
                                           "Udyr",
                                           "Urgot",
                                           "Varus",
                                           "Vayne",
                                           "Veigar",
                                           "Vel\u0027Koz",
                                           "Vex",
                                           "Vi",
                                           "Viego",
                                           "Viktor",
                                           "Vladimir",
                                           "Volibear",
                                           "Warwick",
                                           "Wukong",
                                           "Xayah",
                                           "Xerath",
                                           "XinZhao",
                                           "Yasuo",
                                           "Yone",
                                           "Yorick",
                                           "Yunara",
                                           "Yuumi",
                                           "Zac",
                                           "Zed",
                                           "Zeri",
                                           "Ziggs",
                                           "Zilean",
                                           "Zoe",
                                           "Zyra"
                                       ],
                  "banPickMode":  [
                                      "Master",
                                      "Counter",
                                      "Strong",
                                      "Season",
                                      "Match-up"
                                  ]
              }
};