const MCP_URL='https://mcp-api.op.gg/mcp';
const JSON_HEADERS={'Content-Type':'application/json','Accept':'application/json, text/event-stream'};
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'POST,OPTIONS'};

function json(data,status=200,cache='no-store'){return new Response(JSON.stringify(data),{status,headers:{...CORS,'Content-Type':'application/json; charset=utf-8','Cache-Control':cache}})}
async function mcpPost(body,session=''){const headers={...JSON_HEADERS};if(session)headers['mcp-session-id']=session;const response=await fetch(MCP_URL,{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(18000)});if(!response.ok)throw new Error(`OP.GG MCP ${response.status}`);return {payload:await response.json(),session:response.headers.get('mcp-session-id')||session}}
async function mcpSession(){const {session}=await mcpPost({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'lol-analyst',version:'1.0.0'}}});if(!session)throw new Error('OP.GG MCP did not create a session');return session}
async function mcpTool(session,id,name,args){const {payload}=await mcpPost({jsonrpc:'2.0',id,method:'tools/call',params:{name,arguments:args}},session);if(payload.error)throw new Error(payload.error.message||'OP.GG tool failed');const text=payload.result?.content?.find(item=>item.type==='text')?.text;if(!text)throw new Error('OP.GG returned no readable data');return text}
function unquote(value=''){return value.replace(/\\"/g,'"').replace(/\\\\/g,'\\')}
function parseProfile(text,region){const identity=text.match(/LolGetSummonerProfile\(Data\(Summoner\("((?:\\"|[^"])*)","((?:\\"|[^"])*)","((?:\\"|[^"])*)",(\d+)/),champions=new Map(),championPattern=/ChampionStat\("((?:\\"|[^"])*)",\d+,(\d+),(\d+),(\d+)\)/g,seasons=[...text.matchAll(/PreviousSeason\((\d+)\)/g)].map(match=>Number(match[1]));for(const match of text.matchAll(championPattern)){const name=unquote(match[1]),entry={name,play:Number(match[2]),win:Number(match[3]),lose:Number(match[4])},current=champions.get(name);if(!current||entry.play>current.play)champions.set(name,entry)}if(!identity)throw new Error('Summoner was not found in this region');return {gameName:unquote(identity[1]),tagLine:unquote(identity[2]),profileImage:unquote(identity[3]),level:Number(identity[4]),region,seasonCount:new Set(seasons).size,seasons:[...new Set(seasons)],champions:[...champions.values()].sort((a,b)=>b.play-a.play||b.win-a.win)}}
function parseLane(text){const pattern=/(?:Top|Jungle|Mid|Adc|Support)\("((?:\\"|[^"])*)",(\d+),(\d+),([\d.]+),([\d.]+),([\d.]+)\)/g;return [...text.matchAll(pattern)].map(match=>({champion:unquote(match[1]),tier:Number(match[2]),rank:Number(match[3]),winRate:Number(match[4]),pickRate:Number(match[5]),banRate:Number(match[6])})).sort((a,b)=>a.rank-b.rank).slice(0,50)}
async function profile(body){const gameName=String(body.gameName||'').trim(),tagLine=String(body.tagLine||'').trim(),region=String(body.region||'VN').trim().toUpperCase();if(!gameName||!tagLine||gameName.length>40||tagLine.length>12)throw new Error('Riot ID is invalid');const session=await mcpSession(),text=await mcpTool(session,2,'lol_get_summoner_profile',{game_name:gameName,tag_line:tagLine,region,lang:'vi_VN',desired_output_fields:['data.summoner.{game_name,tagline,profile_image_url,level}','data.summoner.most_champions.champion_stats[].{champion_name,id,play,win,lose}','data.summoner.ranked_most_champions.my_champion_stats[].{champion_name,id,play,win,lose}','data.summoner.recent_champion_stats[].{champion_name,id,play,win}','data.summoner.previous_seasons[].season_id']});return parseProfile(text,region)}
async function meta(){const session=await mcpSession(),positions={},lanes=['top','jungle','mid','adc','support'];for(let index=0;index<lanes.length;index++){const lane=lanes[index],text=await mcpTool(session,index+2,'lol_list_lane_meta_champions',{position:lane,lang:'en_US',desired_output_fields:[`data.positions.${lane}[].{champion,tier,rank,win_rate,pick_rate,ban_rate}`]});positions[lane]=parseLane(text)}return {positions,updatedAt:new Date().toISOString(),source:'OP.GG MCP'}}

export async function onRequestOptions(){return new Response(null,{status:204,headers:CORS})}
export async function onRequestPost({request}){try{const body=await request.json();if(body.action==='profile')return json(await profile(body));if(body.action==='meta')return json(await meta(),200,'public, max-age=1800');return json({error:'Unknown action'},400)}catch(error){return json({error:error instanceof Error?error.message:'OP.GG request failed'},502)}}
