import {writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';

const MCP_URL='https://mcp-api.op.gg/mcp';
const lanes=['top','jungle','mid','adc','support'];
const headers={'Content-Type':'application/json','Accept':'application/json, text/event-stream'};

async function post(body,session=''){
  const requestHeaders={...headers};
  if(session)requestHeaders['mcp-session-id']=session;
  const response=await fetch(MCP_URL,{method:'POST',headers:requestHeaders,body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});
  if(!response.ok)throw new Error(`OP.GG MCP ${response.status}`);
  return {payload:await response.json(),session:response.headers.get('mcp-session-id')||session};
}

async function tool(session,id,name,args){
  const {payload}=await post({jsonrpc:'2.0',id,method:'tools/call',params:{name,arguments:args}},session);
  if(payload.error)throw new Error(payload.error.message||'OP.GG tool failed');
  const text=payload.result?.content?.find(item=>item.type==='text')?.text;
  if(!text)throw new Error('OP.GG returned no readable data');
  return text;
}

function parseLane(text){
  const pattern=/(?:Top|Jungle|Mid|Adc|Support)\("((?:\\"|[^"])*)",(\d+),(\d+),([\d.]+),([\d.]+),([\d.]+)\)/g;
  return [...text.matchAll(pattern)].map(match=>({champion:match[1].replace(/\\"/g,'"').replace(/\\\\/g,'\\'),tier:Number(match[2]),rank:Number(match[3]),winRate:Number(match[4]),pickRate:Number(match[5]),banRate:Number(match[6])})).sort((a,b)=>a.rank-b.rank).slice(0,50);
}

const initialized=await post({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'lol-analyst-meta-sync',version:'1.0.0'}}});
if(!initialized.session)throw new Error('OP.GG MCP did not create a session');
const positions={};
for(const [index,lane] of lanes.entries()){
  const text=await tool(initialized.session,index+2,'lol_list_lane_meta_champions',{position:lane,lang:'en_US',desired_output_fields:[`data.positions.${lane}[].{champion,tier,rank,win_rate,pick_rate,ban_rate}`]});
  positions[lane]=parseLane(text);
  if(!positions[lane].length)throw new Error(`No ${lane} meta returned`);
}
const data={positions,updatedAt:new Date().toISOString(),source:'OP.GG MCP · Ranked Solo · Summoner’s Rift'};
await writeFile(resolve('meta-data.js'),`/* Generated by scripts/sync-meta.mjs. */\nglobalThis.LOL_META_DATA=${JSON.stringify(data)};\n`,'utf8');
console.log(`Updated meta-data.js: ${Object.values(positions).reduce((sum,list)=>sum+list.length,0)} lane entries`);
